// Generated by CoffeeScript 1.3.3

jQuery.event.props.push("dataTransfer");

(function() {
  var Avatar, s;
  s = void 0;
  Avatar = {
    settings: {
      bod: $("body"),
      img: $("#image"),
      fileInput: $("#uploader")
    },
    init: function() {
      s = Avatar.settings;
      return Avatar.bindUIActions();
    },
    bindUIActions: function() {
      var timer;
      timer = void 0;
      s.bod.on("dragover", function(event) {
        clearTimeout(timer);
        if (event.currentTarget === s.bod[0]) {
          Avatar.showDroppableArea();
        }
        return false;
      });
      s.bod.on("dragleave", function(event) {
        if (event.currentTarget === s.bod[0]) {
          return timer = setTimeout(function() {
            return Avatar.hideDroppableArea();
          }, 200);
        }
      });
      s.bod.on("drop", function(event) {
        event.preventDefault();
        return Avatar.handleDrop(event.dataTransfer.files);
      });
      return s.fileInput.on("change", function(event) {
        return Avatar.handleDrop(event.target.files);
      });
    },
    showDroppableArea: function() {
      return s.bod.addClass("droppable");
    },
    hideDroppableArea: function() {
      return s.bod.removeClass("droppable");
    },
    handleDrop: function(files) {
      var file;
      Avatar.hideDroppableArea();
      file = files[0];
      if (file.type.match("image.*")) {
        return Avatar.resizeImage(file, 256, function(data) {
          return Avatar.placeImage(data);
        });
      } else {
        return alert("That file wasn't an image.");
      }
    },
    resizeImage: function(file, size, callback) {
      var fileTracker;
      fileTracker = new FileReader;
      fileTracker.onload = function() {
        return Resample(this.result, size, size, callback);
      };
      fileTracker.readAsDataURL(file);
      fileTracker.onabort = function() {
        return alert("The upload was aborted.");
      };
      return fileTracker.onerror = function() {
        return alert("An error occured while reading the file.");
      };
    },
    placeImage: function(data) {
      return s.img.attr("src", data);
    }
  };
  return Avatar.init();
})();
